### ISSUE TITLE
关于S2-046中的一些问题

### ISSUE THREAD

**Issue by Jun-5heng** [Vancomycin-g/Struts2Scan#1]
作者您好，我在使用工具过程中发现在class S2-046中检测用payload字符串中使用的"\0"空字符，在requests库中以post方式传递的时候生成的数据包中"\0"会被编码成%00导致漏洞检测失败，请问有没有什么解决办法，找了很久都没能解决这个问题

**Comment by Vancomycin-g** [comment]
那你能不能把相关的靶场给我，我调试看看

**Comment by Vancomycin-g** [comment]
> 作者您好，我在使用工具过程中发现在class S2-046中检测用payload字符串中使用的"\0"空字符，在requests库中以post方式传递的时候生成的数据包中"\0"会被编码成%00导致漏洞检测失败，请问有没有什么解决办法，找了很久都没能解决这个问题



> 您好，我在使用工具过程中发现在 S2-046 类中检测使用有效载荷字符串中使用的“\0”空字符，在请求库中以邮寄方式传送的时候生成的数据包中的“\0” “会被编码成%00导致漏洞检测无法解决，请问有什么没有办法解决，找不到解决这个问题的办

> 您好，在使用字符串类中检测使用有效的中2S-046字符串中的“\0”字样，在使用过程中生成的数据包中的“\0”字样，在使用过程中生成的数据包0”“被编码成%00导致漏洞检测无法解决，请问会有什么没有办法解决，找不到解决这个问题的办法

好的，我看看，你burp中复现成功了吗

**Comment by Vancomycin-g** [comment]
额，抱歉，github评论没有回复过，不小心删了，你burp中复现成功了嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vancomycin-g/Struts2Scan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 晚上7:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Vancomycin-g/Struts2Scan] 关于S2-046中的一些问题 (Issue #1)





 
作者您好，我在使用工具过程中发现在class S2-046中检测用payload字符串中使用的"\0"空字符，在requests库中以post方式传递的时候生成的数据包中"\0"会被编码成%00导致漏洞检测失败，请问有没有什么解决办法，找了很久都没能解决这个问题

**Comment by Jun-5heng** [comment]
> 额，抱歉，github评论没有过回复，不小心删了，你打嗝中复现成功了嘛
> […](#)
> ------------------ 原始邮件 ------------------ 发件人：“万古霉素-g /Struts2Scan" ***@***.***>; 发送时间： 2022 年 5 月 2 日（星期一）晚上 7:55 ***@***.***>; ***@***.***>; 主题： [Vancomycin-g/Struts2Scan] 关于 S2-046 中的一些问题（问题#1）作者您好，我在使用工具过程中发现在课堂 S2-046 中检测用有效负载字符串中使用的“ \0"字符，在请求库中传递的时候生成的数据包中没有\0"会被编码成000导致漏洞检测失败，请求方式有%没有什么办法，找很久才能解决这个问题——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

我在burp中复现成功了，明确确定是空字符被url编码的问题，漏洞环境的话是docker——2d8ru/struts2

**Comment by Vancomycin-g** [comment]
> > 额，抱歉，github评论没有过回复，不小心删了，你打嗝中复现成功了嘛
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人：“万古霉素-g /Struts2Scan" _**@**_._**>; 发送时间： 2022 年 5 月 2 日（星期一）晚上 7:55 _**@**_.**_>; _**@**_._**>; 主题： [Vancomycin-g/Struts2Scan] 关于 S2-046 中的一些问题（问题#1）作者您好，我在使用工具过程中发现在课堂 S2-046 中检测用有效负载字符串中使用的“ \0"字符，在请求库中传递的时候生成的数据包中没有\0"会被编码成000导致漏洞检测失败，请求方式有%没有什么办法，找很久才能解决这个问题——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您订阅了此线程。消息 ID：**_@_**.**_>
> 
> 我在burp中复现成功了，明确确定是空字符被url编码的问题，漏洞环境的话是docker——2d8ru/struts2

在你说的那个漏洞环境中，就是只要把%00换成16进制00就可以了是吧

**Comment by Vancomycin-g** [comment]
> > > 额，抱歉，github评论没有过回复，不小心删了，你打嗝中复现成功了嘛
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人：“万古霉素-g /Struts2Scan" _**@**_._**>; 发送时间： 2022 年 5 月 2 日（星期一）晚上 7:55 _**@**_.**_>; _**@**_._**>; 主题： [Vancomycin-g/Struts2Scan] 关于 S2-046 中的一些问题（问题#1）作者您好，我在使用工具过程中发现在课堂 S2-046 中检测用有效负载字符串中使用的“ \0"字符，在请求库中传递的时候生成的数据包中没有\0"会被编码成000导致漏洞检测失败，请求方式有%没有什么办法，找很久才能解决这个问题——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您订阅了此线程。消息 ID：**_@_**.**_>
> > 
> > 
> > 我在burp中复现成功了，明确确定是空字符被url编码的问题，漏洞环境的话是docker——2d8ru/struts2
> 
> 在你说的那个漏洞环境中，就是只要把%00换成16进制00就可以了是吧

我复现试试

**Comment by Vancomycin-g** [comment]
> 作者您好，我在使用工具过程中发现在class S2-046中检测用payload字符串中使用的"\0"空字符，在requests库中以post方式传递的时候生成的数据包中"\0"会被编码成%00导致漏洞检测失败，请问有没有什么解决办法，找了很久都没能解决这个问题

2249854201@qq.com 加我
