### ISSUE TITLE
（s2-046问题）评论不小心删了。。。

### ISSUE THREAD

**Issue by Vancomycin-g** [Vancomycin-g/Struts2Scan#2]
刚才那个小伙伴，由于没有回复过，回复过程中不小心删了评论，抱歉，你burp中复现成功了嘛

**Comment by Jun-5heng** [comment]
> 刚才那个小伙伴，由于没有过回复，回复过程中不小心删了评论，抱歉，你打嗝中复现成功了嘛

不是吧，我幸亏回来看了一下hhh，我这边在burp复现成功了，不方便的话你可以留个邮箱我将图片之类的东西发给你

**Comment by Vancomycin-g** [comment]
> > 刚才那个小伙伴，由于没有过回复，回复过程中不小心删了评论，抱歉，你打嗝中复现成功了嘛
> 
> 不是吧，我幸亏回来看了一下hhh，我这边在burp复现成功了，不方便的话你可以留个邮箱我将图片之类的东西发给你

2249854201@qq.com  我是有个046的环境，但手动复现都复现不出来，然后按照你说的我本地环境都没有搭建好。。人麻了
